from building import *

src = Glob('*.c') + Glob('*.cpp')
cwd = GetCurrentDir()

CPPPATH = [cwd]
group = DefineGroup('', src, depend = [''], CPPPATH=CPPPATH)

# add C++ runtime wrapper
group = group + SConscript('runtime/SConscript')

Return('group')
